Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -3,16 +3,15 @@ stages:
   jobs:
   - job: windows_setup
     pool:
-      vmImage: 'windows-2025'
+      vmImage: 'windows-2025'  # Use the appropriate Windows version
     timeoutInMinutes: 9999
     steps:
-
-    # Install ngrok via WinGet
     - powershell: |
-        Write-Host "Installing ngrok using WinGet..."
-        winget install --id Ngrok.Ngrok --accept-package-agreements --accept-source-agreements
-        ngrok config add-authtoken $Env:NGROK_AUTH_TOKEN
-      displayName: 'Install and configure ngrok (WinGet)'
+        # Download and Setup ngrok
+        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
+        Expand-Archive ngrok.zip
+        .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
+      displayName: 'Download and Setup ngrok'
 
     - powershell: |
         # Configure Remote Desktop
@@ -23,14 +22,24 @@ stages:
 
     - powershell: |
         # Create User runneradmin
-        echo "Checking if user 'runneradmin' exists..."
+        echo "Checking if user 'runneradmin' exists before creating..."
         $existingUser = Get-LocalUser -Name 'runneradmin' -ErrorAction SilentlyContinue
-        if (-not $existingUser) {
-            New-LocalUser -Name 'runneradmin' -Password (ConvertTo-SecureString $env:ADMIN_PASSWORD -AsPlainText -Force) -PasswordNeverExpires:$true -AccountNeverExpires:$true
-            Add-LocalGroupMember -Group 'Administrators' -Member 'runneradmin'
+        if ($existingUser) {
+            echo "User 'runneradmin' already exists."
+        } else {
+            echo "User 'runneradmin' does not exist or an error occurred."
+            $userCreationOutput = New-LocalUser -Name 'runneradmin' -Password (ConvertTo-SecureString $env:ADMIN_PASSWORD -AsPlainText -Force) -PasswordNeverExpires:$true -AccountNeverExpires:$true -ErrorAction Stop
+            if ($userCreationOutput) {
+                echo "User 'runneradmin' created successfully."
+                Add-LocalGroupMember -Group 'Administrators' -Member 'runneradmin' -ErrorAction Stop
+            } else {
+                echo "Error creating user 'runneradmin': $userCreationOutput"
+                exit 1
+            }
         }
       displayName: 'Create User runneradmin'
 
     - powershell: |
-        ngrok tcp 3389
+        # Run ngrok for RDP
+        .\ngrok\ngrok.exe tcp 3389
       displayName: 'Run ngrok for RDP'
